---
# System Integration Role - Configuration Symlinking
# Makes the qtile repository the single source of truth for all configurations

- name: Make scripts executable
  shell: |
    find {{ qtile_home }}/.config/qtile -name "*.sh" -type f -exec chmod +x {} \;
  become_user: "{{ qtile_user }}"

- name: Create user .config directory
  file:
    path: "{{ qtile_home }}/.config"
    state: directory
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    mode: '0755'

- name: Backup existing configuration directories
  block:
    - name: Check for existing config directories
      stat:
        path: "{{ qtile_home }}/.config/{{ item }}"
      register: existing_configs
      loop:
        - dunst
        - touchegg
        - rofi
        - conky

    - name: Backup existing directories that aren't symlinks
      command: mv "{{ qtile_home }}/.config/{{ item.item }}" "{{ qtile_home }}/.config/{{ item.item }}.backup.{{ ansible_date_time.epoch }}"
      when: item.stat.exists and not item.stat.islnk
      loop: "{{ existing_configs.results }}"
      loop_control:
        label: "{{ item.item }}"
      become_user: "{{ qtile_user }}"

- name: Create directory symlinks for configuration folders
  file:
    src: "{{ qtile_home }}/.config/qtile/install/{{ item }}"
    dest: "{{ qtile_home }}/.config/{{ item }}"
    state: link
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    force: yes  # Replace existing symlinks
  loop:
    - dunst
    - touchegg
    - rofi
    - conky
  become_user: "{{ qtile_user }}"

- name: Check for existing standalone config files
  stat:
    path: "{{ qtile_home }}/.config/{{ item }}"
  register: existing_files
  loop:
    - picom.conf

- name: Backup existing standalone config files
  command: mv "{{ qtile_home }}/.config/{{ item.item }}" "{{ qtile_home }}/.config/{{ item.item }}.backup.{{ ansible_date_time.epoch }}"
  when: item.stat.exists and not item.stat.islnk
  loop: "{{ existing_files.results }}"
  loop_control:
    label: "{{ item.item }}"
  become_user: "{{ qtile_user }}"

- name: Create file symlinks for standalone configurations
  file:
    src: "{{ qtile_home }}/.config/qtile/install/{{ item }}"
    dest: "{{ qtile_home }}/.config/{{ item }}"
    state: link
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    force: yes
  loop:
    - picom.conf
  become_user: "{{ qtile_user }}"

- name: Copy X11 configuration files
  copy:
    src: "{{ qtile_home }}/.config/qtile/install/X11/{{ item }}"
    dest: "/etc/X11/xorg.conf.d/{{ item }}"
    mode: '0644'
    backup: yes
  loop:
    - 40-libinput-touchpad.conf
  ignore_errors: yes

- name: Set up systemd user services directory
  file:
    path: "{{ qtile_home }}/.config/systemd/user"
    state: directory
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    mode: '0755'

- name: Copy systemd user service files
  shell: |
    find {{ qtile_home }}/.config/qtile/install -name "*.service" -type f -exec cp {} {{ qtile_home }}/.config/systemd/user/ \;
    chown {{ qtile_user }}:{{ qtile_user }} {{ qtile_home }}/.config/systemd/user/*.service
  ignore_errors: yes

- name: Detect if system has battery (laptop detection)
  stat:
    path: /sys/class/power_supply/BAT0
  register: battery_check

- name: Set up battery monitoring cron job (laptops only)
  cron:
    name: "Battery monitor"
    minute: "*/10"
    job: "{{ qtile_home }}/.config/qtile/install/battery-monitor.sh"
    user: "{{ qtile_user }}"
  when: battery_check.stat.exists

- name: Run brightness permissions setup script
  command: "{{ qtile_home }}/.config/qtile/install/setup-brightness-permissions.sh"
  args:
    creates: /etc/udev/rules.d/90-backlight.rules

- name: Enable touchegg system service
  systemd:
    name: touchegg.service
    enabled: yes
    state: started
  ignore_errors: yes

- name: Enable systemd user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
    daemon_reload: yes
  become_user: "{{ qtile_user }}"
  with_items:
    - auto-rotate.service
    - monitor-manager.service
  ignore_errors: yes

- name: Display configuration symlinks status
  debug:
    msg: |
      === CONFIGURATION SYMLINKS CREATED ===
      Directory symlinks (entire folders managed by git):
      ~/.config/dunst -> ~/.config/qtile/install/dunst
      ~/.config/touchegg -> ~/.config/qtile/install/touchegg  
      ~/.config/rofi -> ~/.config/qtile/install/rofi
      ~/.config/conky -> ~/.config/qtile/install/conky
      
      File symlinks:
      ~/.config/picom.conf -> ~/.config/qtile/install/picom.conf
      
      Repository is now the single source of truth for all configurations!