---
- name: Install fontconfig
  package:
    name: fontconfig
    state: present

- name: Create fonts directory
  file:
    path: /usr/share/fonts/truetype/jetbrainsmono
    state: directory
    mode: '0755'

- name: Check if fonts directory exists
  stat:
    path: "{{ playbook_dir }}/../install/fonts"
  register: fonts_dir

- name: Copy JetBrainsMono fonts to system fonts directory
  copy:
    src: "{{ playbook_dir }}/../install/fonts/"
    dest: /usr/share/fonts/truetype/jetbrainsmono/
    mode: '0644'
  when: fonts_dir.stat.exists
  notify: update font cache

- name: Install JetBrainsMono from package manager as fallback
  package:
    name: fonts-jetbrains-mono
    state: present
  when: not fonts_dir.stat.exists
  ignore_errors: yes

- name: Update font cache
  command: fc-cache -fv
  notify: update font cache

- name: Display font installation status
  debug:
    msg: "JetBrainsMono Nerd Fonts installed from {{ playbook_dir }}/../install/fonts/"
  when: fonts_dir.stat.exists

- name: Display font fallback message
  debug:
    msg: "INFO: install/fonts directory not found - installed from package manager instead. Place JetBrainsMono Nerd Font files in install/fonts/ for full icon support"
  when: not fonts_dir.stat.exists