---
# Safe repository setup using information from failsafe-checks
- name: Clone or update qtile dotfiles repository (safe mode)
  git:
    repo: https://github.com/stonecharioteer/dotfiles-qtile.git
    dest: "{{ qtile_home }}/.config/qtile"
    version: main
    update: "{{ not qtile_config_repo_exists }}"  # Only update if it's a new clone
    force: no  # Never force, to preserve local changes
  become_user: "{{ qtile_user }}"
  when: not qtile_config_repo_exists

- name: Update existing qtile repository (safe mode)
  shell: |
    cd {{ qtile_home }}/.config/qtile
    git fetch origin
    echo "Repository updated, but not merged to preserve local changes"
  become_user: "{{ qtile_user }}"
  when: qtile_config_repo_exists
  register: git_fetch_result
  changed_when: false

- name: Display git status for existing repository
  shell: |
    cd {{ qtile_home }}/.config/qtile
    echo "=== Current Branch ==="
    git branch --show-current
    echo "=== Git Status ==="
    git status --porcelain
    echo "=== Uncommitted Changes ==="
    git diff --name-only
  become_user: "{{ qtile_user }}"
  when: qtile_config_repo_exists
  register: git_status_result
  changed_when: false

- name: Show git repository status
  debug:
    msg: |
      === QTILE REPOSITORY STATUS ===
      {% if qtile_config_repo_exists %}
      Repository exists - preserved existing checkout
      {{ git_status_result.stdout }}
      {% else %}
      Repository cloned fresh from GitHub
      {% endif %}
  when: qtile_config_repo_exists

- name: Ensure qtile config directory ownership
  file:
    path: "{{ qtile_home }}/.config/qtile"
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    recurse: yes

- name: Clone or update Alacritty repository (safe mode)
  git:
    repo: https://github.com/alacritty/alacritty.git
    dest: "{{ qtile_home }}/code/tools/alacritty"
    version: master
    update: "{{ not alacritty_source_repo_exists }}"  # Only update if it's a new clone
    force: no  # Never force, to preserve local changes
  become_user: "{{ qtile_user }}"
  when: not alacritty_source_repo_exists

- name: Update existing Alacritty repository (safe mode)
  shell: |
    cd {{ qtile_home }}/code/tools/alacritty
    git fetch origin
    echo "Alacritty repository updated, but not merged to preserve local changes"
  become_user: "{{ qtile_user }}"
  when: alacritty_source_repo_exists
  register: alacritty_fetch_result
  changed_when: false

- name: Show Alacritty repository status
  debug:
    msg: |
      === ALACRITTY REPOSITORY STATUS ===
      {% if alacritty_source_repo_exists %}
      Repository exists - preserved existing checkout
      {% else %}
      Repository cloned fresh from GitHub
      {% endif %}