---
- name: Install core desktop dependencies
  package:
    name:
      - rofi
      - dunst
      - picom
      - xorg
      - lightdm
      - network-manager-gnome
      - pavucontrol
      - pasystray
      - blueman
      - copyq
      - libnotify-bin
      - cinnamon-screensaver
      - xrandr
      - xinput
      - xset
      - setxkbmap
    state: present

- name: Copy qtile.desktop session file
  copy:
    src: "{{ playbook_dir }}/../install/qtile.desktop"
    dest: /usr/share/xsessions/qtile.desktop
    mode: '0644'

- name: Create .config directory for user
  file:
    path: "{{ qtile_home }}/.config"
    state: directory
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    mode: '0755'