---
- name: Install core desktop dependencies
  package:
    name:
      - rofi
      - dunst
      - picom
      - xorg
      - lightdm
      - network-manager-gnome
      - pavucontrol
      - pasystray
      - blueman
      - copyq
      - libnotify-bin
      - cinnamon-screensaver
      - xrandr
      - xinput
      - xset
      - setxkbmap
      - upower  # For power monitoring functionality
      - powertop  # For detailed power analysis
      - nvidia-smi  # For GPU power monitoring (if NVIDIA GPU present)
    state: present
    ignore_errors: yes  # Some packages might not be available on all systems

- name: Copy qtile.desktop session file
  copy:
    src: "{{ qtile_home }}/.config/qtile/install/qtile.desktop"
    dest: /usr/share/xsessions/qtile.desktop
    mode: '0644'
    remote_src: yes

- name: Create .config directory for user
  file:
    path: "{{ qtile_home }}/.config"
    state: directory
    owner: "{{ qtile_user }}"
    group: "{{ qtile_user }}"
    mode: '0755'